import 'package:flutter/material.dart';

class TheatreListScreenDummyData {
  static const List<Map<String, dynamic>> jsonData = [
    {
      'mytitle': 'Theaters List',
      'myimages': 'assets/kmtheatre.jpg',
      'myfirsttext': 'Kamala Multiplex',
      'mysecondtext': '156 Arcot Road -Vadapalani',
      'mythirdtext': 'Chennai,TamilNadu - 600026',
      'mytimeopen': 'Open',
      'mytimeclose': '. Closes 00:00',
      'myratings': 'Rating : ',
      'myratingsone': '9.8/10',
      'allnumbers': '044 2365 2000',
      'icon1': Icons.access_time_outlined,
      'icon2': Icons.star,
      'icon3': Icons.phone_in_talk_outlined,
    },
    {
      'mytitle': 'Theaters List',
      'myimages': 'assets/vettritheatre.jpg',
      'myfirsttext': 'Vettri Cinemas',
      'mysecondtext': 'No.511,G.S.T,Chromepet',
      'mythirdtext': 'Chennai,TamilNadu - 600044',
      'mytimeopen': 'Open',
      'mytimeclose': '. Closes 00:00',
      'myratings': 'Rating : ',
      'myratingsone': '9.4/10',
      'allnumbers': '044 456 2020',
      'icon1': Icons.access_time_outlined,
      'icon2': Icons.star,
      'icon3': Icons.phone_in_talk_outlined,
    },
    {
      'mytitle': 'Theaters List',
      'myimages': 'assets/pvrtheatre.jpg',
      'myfirsttext': 'PVR Theatre',
      'mysecondtext': 'PVR LTD,Grand Galada Mall,',
      'mythirdtext': 'Chennai,TamilNadu - 600043',
      'mytimeopen': 'Open',
      'mytimeclose': '. Closes 00:00',
      'myratings': 'Rating : ',
      'myratingsone': '7.4/10',
      'allnumbers': '044 2574 2011',
      'icon1': Icons.access_time_outlined,
      'icon2': Icons.star,
      'icon3': Icons.phone_in_talk_outlined,
    },
    {
      'mytitle': 'Theaters List',
      'myimages': 'assets/inoxtheatre.jpg',
      'myfirsttext': 'INOX Theatre',
      'mysecondtext': 'Arcot Road, Virugambakkam',
      'mythirdtext': 'Chennai,TamilNadu - 600042',
      'mytimeopen': 'Open',
      'mytimeclose': '. Closes 00:00',
      'myratings': 'Rating : ',
      'myratingsone': '8.4/10',
      'allnumbers': '044 2574 2011',
      'icon1': Icons.access_time_outlined,
      'icon2': Icons.star,
      'icon3': Icons.phone_in_talk_outlined,
    },
  ];
}
